branches:
  - "main" # TODO remove
  - "release"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  -
    - "@semantic-release/github"
    - draftRelease: true
