[package]
name = "web-index"
version = "1.0.0"
edition = "2021"

# MSRV
rust-version = "1.74.0"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
url = { version = "2.5.2", features = ["serde"] }
